---
driver:
  name: vagrant
  require_chef_omnibus: true
  customize:
    memory: 2048

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver:
      box: box-cutter/ubuntu1404

suites:
  - name: default
    run_list:
      - recipe[bosh-jumpbox::default]
